### ISSUE TITLE
ft.ftr_match vs. ft.fts_match

### ISSUE THREAD

**Issue by patfla** [dmort27/panphon#1]
Hi - experienced programmer and linguist but new to panphon.

Getting started, the documentation has a couple of lines of code.  Run ft.ftr_match and it seems no longer a part of the package so substituted ft.fts_match although I have no idea if they're the same.  I'd compare documentation (in my python interpreter: help(ft.fts_match) ) - except ft.ftr_match is no longer there.

**Comment by dmort27** [comment]
@patfla, It appears that the documentation had grown stale on this point. There is no longer a method FeatureTable.ftr_match, nor an equivalent function. I'm editing the README. Do you need a method that does this (checks if a segment has a set of feature specifications)?

**Comment by patfla** [comment]
@dmort27 thanks David.  No, don't need.  I'm just checking the package out and noticed the discrepancy.

I'll know better what I need when I know what I'm doing - and haven't visited linguistic concepts in a while.
