### ISSUE TITLE
Not enough weights for weighted distance

### ISSUE THREAD

**Issue by ebrahimebrahim** [dmort27/panphon#11]
I think the table `data/feature_weights.csv` is missing a column for "velaric".

This messes up weighted distance. For example distinct feature vectors can have distance 0:
```
import panphon.featuretable
ft = panphon.featuretable.FeatureTable()
a_long,a_short = ft.word_fts('aː ă')
print(a_long)
print(a_short)
print(a_long.weighted_distance(a_short))
```
yields
```
<Segment [+syl, +son, -cons, +cont, -delrel, -lat, -nas, 0strid, +voi, -sg, -cg, 0ant, -cor, 0distr, -lab, -hi, +lo, +back, -round, -velaric, +tense, +long]>
<Segment [+syl, +son, -cons, +cont, -delrel, -lat, -nas, 0strid, +voi, -sg, -cg, 0ant, -cor, 0distr, -lab, -hi, +lo, +back, -round, -velaric, +tense, -long]>
0.0
```
but they differ in the last feature.

I think the fix is just to add the missing column into `feature_weights.csv`, but I don't know what would be a suitable weight.

---

By the way, just really curious, how did you pick those weights? I saw this:
```
The cost of changine an articulatory feature is weighted according to
 the class of the feature and the subjective probability of the
 feature changing in phonological alternation and loanword contexts.
 These weights are stored in `Distance.weights`.
```
but I'm interested if you can give a bit more detail on the kind of insight that went into picking the weights.

**Comment by ebrahimebrahim** [comment]
By the way there's just one pair of rows in `ipa_base.csv` where all features are identical except for "velaric": [ʘ](https://en.wikipedia.org/wiki/Bilabial_click) and [k͡p](https://en.wikipedia.org/wiki/Voiceless_labial%E2%80%93velar_stop). The weight that needs to be filled in would end up being the distance between those two...

**Comment by dmort27** [comment]
Thanks, @ebrahimebrahim! I'll work on fixing these as soon as I can.
