### ISSUE TITLE
accept both single and double-story g

### ISSUE THREAD

**Issue by lxkain** [dmort27/panphon#2]
At the moment, only the single story g (ord = 609) is accepted. However, it would be nice if the double story g ("g") was also accepted (ord = 103). From [(https://en.wikipedia.org/wiki/Voiced_velar_stop)]:

Strictly, the IPA symbol is the so-called single-story G Opentail g.svg, but the double-story G Looptail g.svg is considered an acceptable alternative. The Unicode character "LATIN SMALL LETTER G" (U+0067) renders as either a single-storey G or a double-storey G depending on font while the character "Latin small letter script G" (U+0261) is always a single-story G, but it is generally available only in fonts with the IPA Extensions Unicode character block.

**Comment by dmort27** [comment]
@lxkain, I'm not willing to make this change as a default. I rely on PanPhon only to accept standard IPA and use it to validate the output of my other components. I might consider a keyword argument norm_var that turns on variant normalization. In the meantime, it should be easy enough for you to normalize the input to PanPhon yourself (replace all instances of "g" with "ɡ").

**Comment by lxkain** [comment]
OK, fair enough, thank you for replying to my request. It appears that some professional tools (e.g. Praat) are emitting the non-standard g. I'll handle the g remapping in some adapter code.

**Comment by dmort27** [comment]
Are you referring to particular Praat scripts? Praat should be able to emit either "ɡ" (ord = 609) or "g" (ord = 103) with equal facility depending on scripts and input data.

**Comment by lxkain** [comment]
I'm not... what I know is that I received IPA transcriptions from an expert SLP, and all symbols passed except for "g".
