### ISSUE TITLE
Deprecation warning yaml

### ISSUE THREAD

**Issue by peterdekker** [dmort27/panphon#24]
Thanks for this useful software package. When I create an instance of the panphon.distance.Distance() object, it gives me a deprecation warning, about the used call of the yaml library:

```
/usr/local/lib/python3.6/dist-packages/panphon/distance.py:73: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  dogol_prime = yaml.load(f.read())
```
Would it be possible to replace this yaml call?

**Comment by joanise** [comment]
This was fixed in commit [a910d1f](https://github.com/dmort27/panphon/commit/a910d1f6cec893fac6424cf91289d2247da41a8e) and PR #21.

**Comment by dmort27** [comment]
I've uploaded the newest version to PyPI.

**Comment by joanise** [comment]
Sweet, much appreciated!

**Comment by joanise** [comment]
PS: just a nudge, don't forget to tag 0.19 in GitHub too, so we can know in the future what version here got pushed to PyPI. - Thanks again for pushing 0.19 to PyPI.

**Comment by dmort27** [comment]
Thanks for the reminder.

**Comment by dmort27** [comment]
Tagged 0.19 on GitHub.
