### ISSUE TITLE
*dolgo_prime_distance

### ISSUE THREAD

**Issue by martino-vic** [dmort27/panphon#28]
I really appreciate this package - it has turned out so useful in many situations, many thanks to the authors! One small formal thing that doesn't change the functionality: It looks to me that the guy was called "[Dolgopolsky](https://en.wikipedia.org/wiki/Aharon_Dolgopolsky)" not "Dogolpolsky" (except if there's some pun that I'm missing here?) in that case it should be dolgo_prime_distance

**Comment by dmort27** [comment]
Fixed.

**Comment by aboudev** [comment]
Seems there are similar typos in the [readme section](https://github.com/dmort27/panphon#the-panphondistance-module).
