### ISSUE TITLE
separating base and diacritic

### ISSUE THREAD

**Issue by lxkain** [dmort27/panphon#4]
Given a segment name (e.g. pʲ), is there an easy way to separate the base and the diacritic?

**Comment by dmort27** [comment]
This functionality does not currently exist but it could be added fairly easily.

**Comment by lxkain** [comment]
If you could give me a hint on how to do it I would be happy to create this. Separate by unicode value, if diacritics live in a separate contiguous region?

**Comment by dmort27** [comment]
Yes. Construct a regular expression like `panphon.SEG_REGEX`, but with groups around the base and diacritics/modifiers (or three groups: base, diacritics, modifiers). Note that PanPhon uses the `regex` library rather than `re` from the python standard library.

**Comment by dmort27** [comment]
In `panphon.permissive`, the groups are already there. It's would only be necessary to add a method to access the groups from a match/sequence of matches.
