### ISSUE TITLE
Is panphon.distance for words only?

### ISSUE THREAD

**Issue by wannaphong** [dmort27/panphon#43]
Hello! I want to use panphon to find the distance of ipa string (the sentence that convert to ipa). Is panphon.distance for words only?

**Comment by dmort27** [comment]
PanPhon distance is for words only. You can calculate distances between sentences in various ways (concatenating the words (treating them as a single world, for example).

**Comment by wannaphong** [comment]
> 

Thank you! I will use . for concatenating the word by assusing all words as  a syllable.
