### ISSUE TITLE
support for 'no audible release'

### ISSUE THREAD

**Issue by lxkain** [dmort27/panphon#6]
Support for the [no-audible-release](https://en.wikipedia.org/wiki/No_audible_release) diacritic (◌̚) is missing. I am not exactly sure where and how to formulate this diacritic rule, would it be similar to:

- marker:  ̚
    name: Unreleased
    position: post
    conditions:
      - son: "-"
        cg: "-"
        cont: "-"
      - cont: "+"
        son: "-"
        voi: "-"
    content:
      sg: "+"

**Comment by dmort27** [comment]
No-audible-release appears allophonically, but is never contrastive, so there is no corresponding feature/feature set in the feature system I am using. See #5.

**Comment by lxkain** [comment]
Thank you for the explanation.
