### ISSUE TITLE
What is the IPA that phanphon accepts?

### ISSUE THREAD

**Issue by LinguList** [dmort27/panphon#7]
We're working on a system that is in some sense similar, in some sense much simpler, but in some sense more general than panphon, and we call it [CLTS](https://github.com/cldf/clts). I was thinking, given that, as I read in #5, you have some specific requirements for the kind of IPA you accept, we could use our system which makes it convenient to correct improper input, to convert to panphon's requirements. Can I find explicit information on this in your code, or is it more implicity (based on diacritics and combinations, etc.)? And a more general question: how would you like to be quoted if we refer to your excellent work?

**Comment by dmort27** [comment]
Sorry for the long lag-time in my reply—my GitHub messages were going in the Trash. Regarding the IPA that PanPhon accepts, it is specified in two places: the base characters that are recognized, including segments with ligature ties like affricates and dually-articulated segments, are specified in ipa_bases.csv. Diacritics and diacritic combinations are specified in the file diacritic_definitions.yml, which consists of a series of rules for adding diacritics and another set of rules for combining them.

If you use PanPhon, or wish to make reference to it, please cite it as:

David R. Mortensen, Patrick Littell, Akash Bharadwaj, Kartik Goyal, Chris Dyer, Lori Levin (2016). "PanPhon: A Resource for Mapping IPA Segments to Articulatory Feature Vectors." Proceedings of COLING 2016, the 26th International Conference on Computational Linguistics: Technical Papers, pages 3475–3484, Osaka, Japan, December 11-17 2016.

I'll add BibTeX to the README.md
